### ISSUE TITLE
RS485

### ISSUE THREAD

**Issue by sorscode** [babroval/ford-eec-iv-diagnostic#1]
I'm looking at data on my logic analyzer I pulled from my EEC-IV car. What is different from Ford RS-485 versus standard so I can decode it?

**Comment by babroval** [comment]
Hello,
 That's a very good question.
You can easy read responses from EECiV ECU with any RS485 device, but EECiV
ECU will not understand your commands because of different time delay. So
if you, for example, send command to EECiV ECU : 'FF B1' then the time
delay between FF and B1 have to be a little bit shorter than the RS485. And
that's the ONLY difference between RS485 and DCL protocols.

Best wishes
Max

**Comment by sorscode** [comment]
Okay, so do you have a list of all the commands and what they correspond too? I really only want to see the live data as a troubleshooting tool. I've been reviewing your code.

**Comment by babroval** [comment]
Hello, Sorry for the delay.
I've just added a map with commands at
https://github.com/babroval/ford-eec-iv-diagnostic/blob/master/DCL_communication_map.pdf

Best wishes
Max

**Comment by babroval** [comment]
Hello Danny
Thanks for your attention to EEC-IV project last summer.
If you still interested, I have uploaded connection video:
https://youtu.be/0mJQrj8HoHk/

Sorry for any inconveniences.
Max
