### ISSUE TITLE
Arduino Uno

### ISSUE THREAD

**Issue by luizguto** [babroval/ford-eec-iv-diagnostic#2]
Hi.

I would like to know is it possible use a arduino uno with a RS485 module to read the data from the eec-iv instead the board that you mension?

I didn’t find the board here um Brazil.

Tks.

**Comment by babroval** [comment]
Hello

Thank for your question. Yes that is possible. But you need to do it
yourself,  because most of EEC-IV cars was produced in middle 1990's, so
the youngest ford Mondeo or Escort (Orion) is about 22 years old, so I
believe that most of those cars are live last days because first: of
corrosion and second: Zetec engines don't live forever, sorry. I think I
gave most of EEC-IV diagnostic information and it took really long time. I
mean that there are many other interesting good cars and projects and it
would be very difficult for me to make another iproject for Arduino or
anything similar, sorry again.

Many thanks
Max

**Comment by luizguto** [comment]
Hello Max

Thank you for your reply.
I bought the crumb128 v4.0. After some problems and doubts, i made it work the connection with the java connection app. But when I try to read the fault code or de data I am getting the 19 A1 result.
I checked the cables and didnt work, do you have some tip to me about that?

Thanks so much.

**Comment by babroval** [comment]
Hello. Sorry to hear about your failed connection. Could you tell me the
number of your ECU or model, year and type of
engine of your car, please and I try to sort it out for you. Many Thanks.
Max

**Comment by luizguto** [comment]
Thanks Max!

My ECU number is 547.906.021.F.
Here is a picture of my ECU:

![IMG_38222](https://user-images.githubusercontent.com/51919251/98700295-cf7a7200-2356-11eb-8b17-7be94f35e268.jpg)
![IMG_3823](https://user-images.githubusercontent.com/51919251/98700413-ea4ce680-2356-11eb-956f-3a84e0f0a342.jpg)

**Comment by babroval** [comment]
Hello.
I can't find any information about your type ECU.
So for DCL there must be two diagnostic twisted wires (pins 18 and 19).
https://en.wikipedia.org/wiki/Ford_EEC

Many Thanks
Max

**Comment by babroval** [comment]
Hello luizguto
Thanks for your attention to EEC-IV project last autumn.
If you still interested, I have uploaded connection video:
https://youtu.be/0mJQrj8HoHk/

Sorry for any inconveniences.
Max

**Comment by Iturton** [comment]
Hi, I want to build this project for my escort. I'm from Perú and I cant find a scanner with live data. I hace 2 quesitos for this project: 
-Can I use CP2102 intead of CP2101?
-Does this project fit for this EEC:
![20220724_233151](https://user-images.githubusercontent.com/117331213/202774212-dabb3c87-897a-440c-9d5d-8c63b669da58.jpg)
![20221015_112005](https://user-images.githubusercontent.com/117331213/202774328-a4354cb5-c892-4094-96bf-aa4906010940.jpg)
![Screenshot_20221118-125508_Gallery](https://user-images.githubusercontent.com/117331213/202774335-b8f50174-c5bd-4dff-beba-81410273a669.jpg)

**Comment by babroval** [comment]
Hi,
Yes, you can use CP2102 instead CP2101
And it will work for your Escort

Many thanks
Max
